use_frameworks!

target 'KNVUNDBaseDevelopPackage_Example' do
  pod 'KNVUNDBaseDevelopPackage', :path => '../'

end

target 'KNVUNDBaseDevelopPackage_Tests' do
    pod 'KNVUNDBaseDevelopPackage', :path => '../'
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
end
